In [1]:
##complex data와 똑같이 40ms로 parsing했음 데이터 4배라고 생각하고 뻥튀기시켜봄 정확도는 10ms와 비슷하게 나옴

import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
import sklearn
from sklearn import svm
from datetime import datetime
import glob
import pickle
import re
from sklearn import preprocessing
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import cross_val_score 
from sklearn.model_selection import GridSearchCV
from scipy import signal

#filename queue
filename_queue=glob.glob('./label/label[0-9]*.csv')
#filename_queue=glob.glob('./label/label[6].csv')


In [2]:
"""training_set2=list()
training_label2=list()
test_set2=list()
test_label2=list()
traininglabel_count2=np.zeros(16)
testlabel_count2=np.zeros(16)
"""
training_set=list()

test_set=list()
training_label=list()
test_label=list()
index=[2,3,4,11,14,15]
label_count=np.zeros(16)
traininglabel_count=np.zeros(16)
testlabel_count=np.zeros(16)
ldata=list()

for filename in filename_queue:
    with open(filename,newline='') as data:
        
        data_set=list()
        data_set2=list()
        data_label=list()
        reader=csv.reader(data)
        label=re.findall('\d+',filename)
        label=int(label[0])
        label_count[label]+=1
        if label in index:
            continue
        if label not in index:
            print('label : ', label)
            for row in reader:
                row[0:]=[float(i) for i in row[0:]]
                X_acc=list(row[i] for i in range(150))
                Y_acc=list(row[i+150] for i in range(150))
                Z_acc=list(row[i+300] for i in range(150))
                X_gyro=list(row[i+450] for i in range(150))
                Y_gyro=list(row[i+600] for i in range(150))
                Z_gyro=list(row[i+750] for i in range(150))

                window=np.array([X_acc[0:25],Y_acc[0:25],Z_acc[0:25],X_gyro[0:25],Y_gyro[0:25],Z_gyro[0:25],
                                  X_acc[25:50],Y_acc[25:50],Z_acc[25:50],X_gyro[25:50],Y_gyro[25:50],Z_gyro[25:50],
                                  X_acc[50:75],Y_acc[50:75],Z_acc[50:75],X_gyro[50:75],Y_gyro[50:75],Z_gyro[50:75],
                                  X_acc[75:100],Y_acc[75:100],Z_acc[75:100],X_gyro[75:100],Y_gyro[75:100],Z_gyro[75:100],
                                  X_acc[100:125],Y_acc[100:125],Z_acc[100:125],X_gyro[100:125],Y_gyro[100:125],Z_gyro[100:125],
                                  X_acc[125:150],Y_acc[125:150],Z_acc[125:150],X_gyro[125:150],Y_gyro[125:150],Z_gyro[125:150]])

                
                window2=np.array([[X_acc[0:25],X_acc[25:50],X_acc[50:75],X_acc[75:100],X_acc[100:125],X_acc[125:150]],
                    [Y_acc[0:25],Y_acc[25:50],Y_acc[50:75],Y_acc[75:100],Y_acc[100:125],Y_acc[125:150]],
                    [Z_acc[0:25],Z_acc[25:50],Z_acc[50:75],Z_acc[75:100],Z_acc[100:125],Z_acc[125:150]]])
               
            
            
                """
                window4=np.array([[X_gyro[0:25],X_gyro[25:50],X_gyro[50:75],X_gyro[75:100],X_gyro[100:125],X_gyro[125:150]],
                    [Y_gyro[0:25],Y_gyro[25:50],Y_gyro[50:75],Y_gyro[75:100],Y_gyro[100:125],Y_gyro[125:150]],
                    [Z_gyro[0:25],Z_gyro[25:50],Z_gyro[50:75],Z_gyro[75:100],Z_gyro[100:125],Z_gyro[125:150]]])
                """
                
                
                
                window_mean=window.mean(axis=-1)
                window_stddev=window.std(axis=-1)
                window_median=np.median(window,axis=-1)
                window_percent25=np.percentile(window,25,axis=-1)
                window_percent75=np.percentile(window,75,axis=-1)
                window_feature=np.array([[window_mean],[window_stddev],[window_median],[window_percent25],[window_percent75]])
                window_feature=window_feature.reshape(180)
                
                #Drop outliers1 
                xm=window_stddev[[0,6,12,18,24,30]].mean(axis=0)
                ym=window_stddev[[1,7,13,19,25,31]].mean(axis=0)
                zm=window_stddev[[2,8,14,20,26,32]].mean(axis=0)
                action=np.mean([xm,ym,zm])
                if(action<0.65):
                    label_count[label]-=1
                    continue
                
                window2=window2.reshape(-1)
                #window_RMS=np.roots(np.square(window2[0:6]).mean(axis=-1))
                #if (label_count[label]>=0):
                data_set.append(window_feature)
                data_set2.append(window2)
                data_label.append(label)
            
                #else:
                #    test_set.append(window_feature)
                #    test_label.append(label)
                #    testlabel_count[label]+=1
                
            from sklearn.manifold import TSNE
            from sklearn.decomposition import PCA
            from sklearn.decomposition import MiniBatchDictionaryLearning
            from sklearn.decomposition import IncrementalPCA
            from sklearn.decomposition import TruncatedSVD


            print(np.shape(data_set2))

            data_set2=np.array(data_set2)
            X_embedded2 = MiniBatchDictionaryLearning(n_components=3,n_iter=1000).fit_transform(data_set2)
            #fig = plt.figure()
            #ax2 = fig.add_subplot(111, projection='3d')
            #for x in X_embedded2:
            #    ax2.scatter(x[0],x[1],x[2]) 
            if(int(label)==12):
                from scipy import stats
                z = np.abs(stats.zscore(X_embedded2))
                #X_embedded2 = X_embedded2[(abs(z) <1.8).all(axis=1)]
                data_set_arr=np.array(data_set)
                data_label_arr=np.array(data_label)
                data_set_arr=data_set_arr[(abs(z) <1.8).all(axis=1)]
                data_label_arr=data_label_arr[(abs(z) <1.8).all(axis=1)]
            else:
                if(int(label)==10):
                    z = np.abs(stats.zscore(X_embedded2))
                    #X_embedded2 = X_embedded2[(abs(z) <1.8).all(axis=1)]
                    data_set_arr=np.array(data_set)
                    data_label_arr=np.array(data_label)
                    data_set_arr=data_set_arr[(abs(z) <2).all(axis=1)]
                    data_label_arr=data_label_arr[(abs(z) <2).all(axis=1)]
                
                else:
                    z = np.abs(stats.zscore(X_embedded2))
                    #X_embedded2 = X_embedded2[(abs(z) <1.8).all(axis=1)]
                    data_set_arr=np.array(data_set)
                    data_label_arr=np.array(data_label)
                    data_set_arr=data_set_arr[(abs(z) <2).all(axis=1)]
                    data_label_arr=data_label_arr[(abs(z) <2).all(axis=1)]

            #print(np.shape(data_set_arr))
            #print(np.shape(data_label_arr))

            for x in data_set_arr:
                training_set.append(x)
            for y in data_label_arr:
                training_label.append(y)
                
                

            #fig2 = plt.figure()
            #ax2 = fig2.add_subplot(111, projection='3d')
            #for x in X_embedded2:
            #    ax2.scatter(x[0],x[1],x[2]) 


label :  12
(248, 450)
label :  8
(68, 450)
label :  7
(68, 450)
label :  5
(136, 450)
label :  13
(36, 450)
label :  9
(72, 450)
label :  10
(136, 450)
label :  0
(124, 450)
label :  1
(130, 450)
label :  6
(228, 450)


In [3]:
X=training_set
y=training_label

print(np.shape(X))

(1125, 180)


In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

#X=preprocessing.minmax_scale(training_set)
#X=preprocessing.robust_scale(training_set)
#X=preprocessing.quantile_transform(training_set)

X=training_set
y=training_label
RF=RandomForestClassifier()
param_grid={
 'n_estimators':[50,80,100,120],
    'max_features':['auto','log2','sqrt'],
    'max_depth':[None]
    #'criterion':['gini','entropy']
}
grid=GridSearchCV(estimator=RF,param_grid=param_grid,cv=10,scoring='accuracy')

In [5]:
grid.fit(X,y)

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             ii

In [6]:
grid.cv_results_

{'mean_fit_time': array([0.26270843, 0.41737652, 0.52841439, 0.63300488, 0.15998025,
        0.25516059, 0.31985765, 0.38362134, 0.26355693, 0.42053401,
        0.52571151, 0.63140855]),
 'std_fit_time': array([0.00352904, 0.00419339, 0.00602504, 0.00452469, 0.00080619,
        0.00305732, 0.00315388, 0.00189487, 0.00311346, 0.00422961,
        0.0045261 , 0.00485274]),
 'mean_score_time': array([0.00346119, 0.00504642, 0.00618095, 0.00725365, 0.00341451,
        0.00507286, 0.00615675, 0.00730021, 0.00337265, 0.00503538,
        0.00615475, 0.007271  ]),
 'std_score_time': array([2.69376027e-04, 2.95045857e-05, 4.55514029e-05, 6.52252405e-05,
        3.35547787e-05, 4.94708440e-05, 4.48964468e-05, 5.14614284e-05,
        3.05461470e-05, 5.11459201e-05, 4.05006364e-05, 4.59358794e-05]),
 'param_max_depth': masked_array(data=[None, None, None, None, None, None, None, None, None,
                    None, None, None],
              mask=[False, False, False, False, False, False, False, F

In [7]:
grid.best_params_

{'max_depth': None, 'max_features': 'log2', 'n_estimators': 100}

In [13]:
RF=RandomForestClassifier(n_estimators=100,max_features='log2',max_depth=None)
RF.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='log2', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
X=preprocessing.quantile_transform(training_set)
ETC=ExtraTreesClassifier()

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/preprocessing/data.py:2553: FutureWarning: The default value of `copy` will change from False to True in 0.23 in order to make it more consistent with the default `copy` values of other functions in :mod:`sklearn.preprocessing.data` and prevent unexpected side effects by modifying the value of `X` inplace. To avoid inplace modifications of `X`, it is recommended to explicitly set `copy=True`
  FutureWarning)


In [10]:
param_grid={
 'n_estimators':[100,200,300],
    'max_features':['auto','sqrt','log2'],
    'max_depth':[17,20,25,30]
    #'criterion':['gini','entropy']
}

grid=GridSearchCV(estimator=ETC,param_grid=param_grid,cv=10,scoring='accuracy')

In [11]:
grid.fit(X,y)


/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=ExtraTreesClassifier(bootstrap=False, class_weight=None,
                                            criterion='gini', max_depth=None,
                                            max_features='auto',
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators='warn', n_jobs=None,
                                            oob_score=False, random_state=None,
                                            verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [17, 20,

In [12]:
grid.cv_results_

{'mean_fit_time': array([0.14427218, 0.28361042, 0.42616277, 0.14347632, 0.28462408,
        0.5011708 , 0.12575331, 0.27143154, 0.4007997 , 0.17258573,
        0.29224048, 0.49721975, 0.1631212 , 0.32369673, 0.4892287 ,
        0.11576753, 0.23251133, 0.35488968, 0.15278878, 0.33340297,
        0.43398263, 0.14520788, 0.29757001, 0.43352721, 0.11040699,
        0.21938951, 0.32808878, 0.1446245 , 0.2876334 , 0.43078008,
        0.1447274 , 0.28762288, 0.43239715, 0.11041403, 0.2191793 ,
        0.32892137]),
 'std_fit_time': array([0.00265995, 0.00134402, 0.00221951, 0.00184146, 0.00207904,
        0.08640575, 0.04237062, 0.07823742, 0.07000632, 0.05121067,
        0.00735766, 0.08406434, 0.04464755, 0.06599995, 0.08606081,
        0.00218385, 0.01231016, 0.02243245, 0.00434163, 0.06442183,
        0.00330274, 0.00068246, 0.01755017, 0.0033968 , 0.0004506 ,
        0.00239864, 0.00109749, 0.00087682, 0.00183463, 0.00257811,
        0.00100091, 0.00122708, 0.00354299, 0.00043333, 0.000

In [14]:
grid.best_params_

{'max_depth': 30, 'max_features': 'sqrt', 'n_estimators': 300}

In [15]:
ETC=ExtraTreesClassifier(max_depth=30,max_features='sqrt',n_estimators=300).fit(X,y)

In [107]:
from sklearn.model_selection import cross_val_predict

y_pred = cross_val_predict(ETC, X, y, cv=10)
conf_mat = confusion_matrix(y, y_pred)
print(conf_mat)

[[109   0   0   4   0   0   0   0   3   0]
 [  0 115   4   3   0   0   0   0   0   0]
 [  0   0 116   8   0   0   0   0   0   0]
 [  0   0   0 204   0   0   0   0   0   0]
 [  0   0   0   0  52   0   0   0   4   0]
 [  0   4   0   5   0  48   0   0   0   0]
 [  0   0   0   0   0   0  48  12   4   0]
 [  0   0   0   0   0   0   1 110   9   0]
 [  0   0   0   0   0   0   4  16 152   4]
 [  0   0   0   0   0   0   0   0   0  28]]


In [14]:
class_names=['face','pouring','clinking','drinking1','tissue','drink2','spoon','chopstick','fork','stir']

X=training_set
y=training_label

#print((test_pred_proba))
#for row in test_pred_proba:
#    print(np.max([row]))
test_pred3=ETC.predict(preprocessing.quantile_transform(X))
print(accuracy_score(test_pred3,training_label))
print(confusion_matrix(test_pred3, training_label))

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/preprocessing/data.py:2553: FutureWarning: The default value of `copy` will change from False to True in 0.23 in order to make it more consistent with the default `copy` values of other functions in :mod:`sklearn.preprocessing.data` and prevent unexpected side effects by modifying the value of `X` inplace. To avoid inplace modifications of `X`, it is recommended to explicitly set `copy=True`
  FutureWarning)


1.0
[[116   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0]
 [  0   0 120   0   0   0   0   0   0   0]
 [  0   0   0 200   0   0   0   0   0   0]
 [  0   0   0   0  57   0   0   0   0   0]
 [  0   0   0   0   0  56   0   0   0   0]
 [  0   0   0   0   0   0  68   0   0   0]
 [  0   0   0   0   0   0   0 128   0   0]
 [  0   0   0   0   0   0   0   0 224   0]
 [  0   0   0   0   0   0   0   0   0  28]]


In [108]:
#SVM
#prepare the data
#prepare the model
#X=preprocessing.minmax_scale(training_set)
#X=preprocessing.robust_scale(training_set)
X=preprocessing.quantile_transform(training_set)
y=training_label
clf = sklearn.svm.SVC(gamma='scale',tol=0.1,probability=True)
scores=cross_val_score(clf,X,y,cv=10,scoring='accuracy')
print(scores.mean())

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/preprocessing/data.py:2553: FutureWarning: The default value of `copy` will change from False to True in 0.23 in order to make it more consistent with the default `copy` values of other functions in :mod:`sklearn.preprocessing.data` and prevent unexpected side effects by modifying the value of `X` inplace. To avoid inplace modifications of `X`, it is recommended to explicitly set `copy=True`
  FutureWarning)


0.9030282821749248


In [109]:
param_grid={
 #'kernel':['linear','poly','rbf','sigmoid'], rbf to be best acc
    'C':[10,20,50,100]}

grid=GridSearchCV(estimator=clf,param_grid=param_grid,cv=10,scoring='accuracy')

In [110]:
grid.fit(X,y)
grid.cv_results_

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'mean_fit_time': array([0.53390267, 0.54411323, 0.53812099, 0.51325831]),
 'std_fit_time': array([0.03704927, 0.06052332, 0.04098229, 0.02844576]),
 'mean_score_time': array([0.01463621, 0.01661682, 0.01529706, 0.01485248]),
 'std_score_time': array([0.00166451, 0.00511245, 0.0024762 , 0.00188217]),
 'param_C': masked_array(data=[10, 20, 50, 100],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10}, {'C': 20}, {'C': 50}, {'C': 100}],
 'split0_test_score': array([0.90990991, 0.90990991, 0.90990991, 0.90990991]),
 'split1_test_score': array([0.95495495, 0.95495495, 0.95495495, 0.95495495]),
 'split2_test_score': array([0.86363636, 0.86363636, 0.86363636, 0.86363636]),
 'split3_test_score': array([0.95454545, 0.95454545, 0.95454545, 0.95454545]),
 'split4_test_score': array([0.96261682, 0.96261682, 0.96261682, 0.96261682]),
 'split5_test_score': array([0.99065421, 0.99065421, 0.99065421, 0.99065421]),
 'split6_test_sc

In [111]:
grid.best_params_

{'C': 10}

In [112]:
SVC=sklearn.svm.SVC(10,probability=True).fit(X,y)

/home/parkj0/anaconda3/envs/venv/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [17]:
#save the model

from joblib import dump, load
filename='./svm.sav'
pickle.dump(SVC,open(filename,'wb'))

NameError: name 'SVC' is not defined

In [18]:
filename='./rf.sav'
pickle.dump(RF,open(filename,'wb'))
dump(RF,'rf.joblib')

['rf.joblib']

In [19]:
filename='./ETC.sav'
pickle.dump(ETC,open(filename,'wb'))
dump(ETC,'ETC.joblib')

['ETC.joblib']